language: python
sudo: false
python:
 - "2.7"
install:
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
script:
 - nosetests tugboat/tests/tests_unit/ --with-coverage
after_success:
 - coveralls
