language: python
sudo: false
python:
 - "2.7"
before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/
    # Install Firefox driver
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
    - tar -xvzf geckodriver-v0.19.1-linux64.tar.gz
    - sudo chmod u+x geckodriver
    - sudo mv geckodriver /usr/bin/
install:
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
script:
 - nosetests tugboat/tests/tests_unit/ --with-coverage
after_success:
 - coveralls
