name: GitHub Actions CI 

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Chrome and Firefox drivers
      run: | 
        wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo chmod u+x chromedriver
        sudo mv chromedriver /usr/bin/
        wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.20.0-linux64.tar.gz
        sudo chmod u+x geckodriver
        sudo mv geckodriver /usr/bin/


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt


    - name: Tests
      run: |
        nosetests tugboat/tests/tests_unit/ --with-coverage
        
    - name: Coveralls
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
